### ISSUE TITLE
Mean Rank metric?

### ISSUE THREAD

**Issue by yjdy** [AvivNavon/nash-mtl#11]
I have run your experment of nyuv2 on my own computer. But I can not find the result of Mean Rank metric, which you reported in the paper. How can I compute the metric by myself?

Thank you very much

**Comment by AvivNavon** [comment]
For computing the Mean Rank (MR), you first need to obtain all results (metrics) for all methods.
Assuming the results are obtained in the form of an array, `results`, with methods for rows and task metrics for columns, you can compute mean rank as follow (not tested):
```python
import numpy as np

results = np.array([...])
order = results.argsort(axis=0)
ranks = order.argsort(axis=0) + 1
method_rank = ranks.mean(1)
```
