### ISSUE TITLE
Error about IMTLG method

### ISSUE THREAD

**Issue by xgxgnpu** [AvivNavon/nash-mtl#2]

**Comment by xgxgnpu** [comment]
Thanks for this great repo, it is very useful!
An error occurs when i run my code with IMTLG method. I am trying to fix it but failed. Could you please give some advice about it. Thank you very much ,anyway. The error is as followed:

`[/content/drive/MyDrive/Colab Notebooks/p42_nash_mtl/methods/weight_methods.py](https://localhost:8080/#) in get_weighted_loss(self, losses, shared_parameters, **kwargs)
    737         )
    738 
--> 739         loss = torch.sum(losses * alpha)
    740         return loss
    741         # return loss, dict(weights=alpha)

TypeError: only integer tensors of a single element can be converted to an index`

**Comment by xgxgnpu** [comment]
I try to run your nash-MTL method, and it is successful！ The nash method you proposed is really effective! Great work!

**Comment by AvivNavon** [comment]
Hi @xgxg1314 , thanks for your interest in our work.
Could you please provide some more details:
- What dataset are you using? 
- Are you trying to use the code we provided as is or did you modify the code?
- If you modified the code, could you please provide a code for reproducing the error?

**Comment by AvivSham** [comment]
Closed due to lack of activity.
