### ISSUE TITLE
Thank you for the great repository.If I don't know which parameter is shared and feed all parameters into method, can I get the right result? 

### ISSUE THREAD

**Issue by yjdy** [AvivNavon/nash-mtl#6]

**Comment by yjdy** [comment]
Thank you for the great repository.
If I don't know which parameter is shared and feed all parameters into method, can I get the right result?

**Comment by yjdy** [comment]
Such as:
        loss, extra_outputs = self.get_weighted_loss(
            losses=losses,
            shared_parameters=all_parameters,
            **kwargs,
        )

**Comment by AvivNavon** [comment]
This may pose some issues and won't work with the provided code:
- `self.get_weighted_loss` calls `torch.autograd.grad` inside: this will raise an error if some of the parameters are not used for creating some loss (for example when trying to differentiate loss of task $i$ w.r.t parameters of task $j$.
- You can specify `allow_unused=True` in `torch.autograd.grad`. However this will return `none` as the grad of unused params.
- You will need to replace this `None` with a zero with a similar shape as the corresponding parameters. 
- This way the code will execute smoothly, and the task-specific parameters will have no effect on e.g. the Nash bargaining solution.

**Comment by AvivSham** [comment]
Closed due to inactivity.
