### ISSUE TITLE
Question about large weights

### ISSUE THREAD

**Issue by yjdy** [AvivNavon/nash-mtl#7]
Thank you for the great work.
When I tried the method, I found that the calculated weights are relatively large than other mtl method,  like [47.24413258, 732.26542343] vs [0.4, 0.6] 

Is it normal?  Should I rescale the weights? Because I think the large weights of losses may influence the regularization.
Thank you!

**Comment by AvivNavon** [comment]
Hi @yjdy, thanks for your interest in our work.
It can be theoretically shown that the solution for Nash-MTL (update direction) has a fixed squared norm equal to the number of tasks. In the code, we clip the norm (by default to 1): https://github.com/AvivNavon/nash-mtl/blob/main/methods/weight_methods.py#L269-L270
There shouldn't be a problem. However, I would add that we didn't see weights these large in our experiments (see figure 7 in Appendix). 
Do you observe some issues with performance?

**Comment by yjdy** [comment]
If I only have two tasks, the norm of output weight vector should be 2. Right?

**Comment by yjdy** [comment]
The norm of output weight vector is much larger than n_tasks in my experiments
Can I rescale the weights vector like this? 
alpha*n_tasks/LA.norm(alpha)

**Comment by yjdy** [comment]
Here is my code
![image](https://user-images.githubusercontent.com/13899680/191409536-a637d1ac-c4e1-4dea-a914-0a9307847206.png)

**Comment by AvivNavon** [comment]
The norm of the weight vector should not equal the number of tasks. The squared weight of the update direction (weighted sum of gradients) should theoretically equal the number of tasks. However, in practice, we clip the weighted gradients so the norm is 1 (see here https://github.com/AvivNavon/nash-mtl/blob/main/methods/weight_methods.py#L269-L270)

**Comment by yjdy** [comment]
I got it. Thank you
