### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by VietHoang1512** [AvivNavon/nash-mtl#8]
Hi @AvivNavon, thank you for your great work. Im trying to experiment with sth new, so could you please give me the log files for NYUv2 experiments so that I can benchmark my running?

**Comment by AvivNavon** [comment]
Hi @VietHoang1512 . 
You can find runs for several methods with full logs for NYUv2 here: https://wandb.ai/geekyrakshit/multi-task-learning?workspace=user-avivnav
While these results are with the SegNet arch., the results are quite similar to MTAN (as we report in the paper).

**Comment by VietHoang1512** [comment]
Thank you for your instant help.  I know that the results of SegNet and MTAN are similar but can I ask how big the gap between  their learning curves are?

**Comment by AvivSham** [comment]
Hi @VietHoang1512.
We don't have such figure that compares MTAN's and SegNet's learning curves, but it should be very easy to create such. Our code supports both models so creating graph like you described should be trivial.

**Comment by VietHoang1512** [comment]
Thank you for your responses, I'm closing the issue now
