### ISSUE TITLE
Questions about the property of convergence on theorem 5.4 and 5.5

### ISSUE THREAD

**Issue by BossunWang** [AvivNavon/nash-mtl#9]
Hi, experts
Thanks sharing the excellent work about MTL.
1. ||1/α(t)||≥σK((G(t))⊤G(t))||α(t)||  on the theorem 5.4, where σK((G(t))⊤G(t)) is the smallest singular value of (G(t))⊤G(t).
* What the type of norm? 
  - I think this is spectral norm, then ||(G(t))⊤G(t)|| is the maximum singular value of (G(t))⊤G(t) such that the Inequality holds. Is this right?
2. As σK((G(t))TG(t))→0 we have from continuity that σK(G⊤ ∗G∗)=0, where G∗is the matrix of gradients at θ∗.
* Is this implication for arriving Pareto optimal point θ∗ we should check the smallest singular value of (G(t))⊤G(t) every iteration to observe whether to converge or not?

**Comment by AvivNavon** [comment]
Hi @BossunWang 
Thanks for your interest in our work.

1. This is the 2-norm (Euclidean norm). There's a known result (https://math.stackexchange.com/questions/2330716/proving-that-the-norm-of-a-matrix-is-bigger-or-equal-to-its-smallest-singular-v) that shows the required inequality in the proof.
2. In the paper, we assume that the gradients are linearly independent unless we are at a Pareto
stationary point. However, note that this generally need not hold; for example, take the degenerate case of two identical tasks.
